MAX_DISTANCE = 1000  # Максимальное расстояние между филиалами
MAX_BRANCH_COUNT = 100  # Максимальное число филиалов
MIN_POPULATION = 100  # Минимальное население
MAX_POPULATION = 10 * 1000 * 1000  # Максимальное население
SLEEP_TIME_SEC = 5  # Время для паузы
MAX_WEIGHT = 500  # Максимальный вес
MAX_DESIRED_COST = MAX_WEIGHT * MAX_DISTANCE  # Максимальная желаемая стоимость
MAX_DESIRED_TIME = 72  # Максимальное желаемое время доставки
SPEED_FACTOR = 1.5  # Ускоряющий коэффиуент для скоростных магистралей
